# Basic site configuration
title:          "Tetsu's Blog"
baseurl:        ""
description:    ""
author:         "Shoto"
permalink:      "/entry/:title"

# The links to display in the TopNav menu.
nav-links:
  about:        "/about"

# Plugin list
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-tidy

# Main pagination configuration for jekyll-paginate-v2
pagination:
  enabled:      "true"
  per_page:     "3"
  permalink:    "/page/:num/"
  sort_reverse: "true"

# Autopage configuration for jekyll-paginate-v2
autopages:
  enabled:      "true"
  categories:
    layouts:
      - "home.html"
    permalink:  "/category/:cat"
  tags:
    layouts:
      - "home.html"
    permalink:  "/tag/:cat"