title:         "Tetsu's Blog"
baseurl:       ""
description:   ""
author:        "Shoto"
permalink:     "/entry/:title"

blog_links:
  stories:     "/"
  about:       "/about"
  archives:    "/archives"

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate:      "5"
paginate_path: "/page/:num"